experiment_name: autogapfill

run_idx: 0
wd: /Users/bezk/Documents/CAM/research_code/ml_informed_gapfill
test_data: ${wd}/data/komodo_scraper/
train_data: ${wd}/data/melanie_data/

models_dir: ${test_data}/intermediate_data/ensemble_models/

model_features_path: ${test_data}/processed_data/model_features.csv
media_features_path: ${train_data}/intermediate/media_features.csv

classifier_path: 'runs:/8e1afa697d21401089094b3760d25802/model'
classifier_run_id: 8e1afa697d21401089094b3760d25802

compound_prefix: X_MEDIA_

proteomes_dir: ${test_data}/intermediate_data/proteomes/
media_db: ${train_data}/raw/melanie_data_media.tsv

species_label: Y_species_label
growth_label: Y_growth_class
