experiment_name: autogapfill

run_idx: 0
wd: ${user.wd}
test_data: ${wd}/data/komodo_scraper/
train_data: ${wd}/data/melanie_data/

models_dir: ${test_data}/intermediate_data/ensemble_models/

model_features_path: ${test_data}/processed_data/model_features.csv
media_features_path: ${train_data}/intermediate/media_features.csv

classifier_path: 'runs:/5503e02c1465460b891366ca88bf94a5/model'
classifier_run_id: 5503e02c1465460b891366ca88bf94a5

compound_prefix: X_MEDIA_

proteomes_dir: ${test_data}/intermediate_data/proteomes/
media_db: ${train_data}/raw/melanie_data_media.tsv

species_label: Y_species_label
growth_label: Y_growth_class


defaults:
  - _self_
  - user: local
