experiment_name: machado_fba_models

run_idx: 0

data_dir: ${user.wd}/data/melanie_data
test_data: ${data_dir}/processed/labelled_monoculture_df.csv


compound_prefix: X_MEDIA_

species_label: Y_species_label
growth_label: Y_growth_class

media_path: ${data_dir}/raw/melanie_data_media.tsv
models_dir: ${data_dir}/models/

defaults:
  - _self_
  - user: local
